accounts/urls.py
from django.urls import path
from accounts.views import *
from django.contrib.auth.views import LogoutView

app_name = 'accounts'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', Login.as_view(), name='login'),
    path('profile/<int:id>/', profile, name='profile'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('edit-profile/<int:pk>/', EditProfile.as_view(), name='edit_profile'),
    path('forget-password/',ForgetPassword.as_view(),name='forget-password'),
    path('password-reset-confirm/<str:uidb64>/<str:token>',CustomPasswordResetConfirmView.as_view(),name='password-reset-confirm'),
]

core/urls.py
from django.urls import path
from core.views import *

app_name = 'core'

urlpatterns = [
    path('', home, name='home'),
    path('story/<int:id>/', story_detail, name='story_detail'),
    path('about/', about, name='about'),
    path('stories/', stories, name='stories'),
    path('recipes/', recipes, name='recipes'),
    path('recipe/<int:id>/', recipe_detail, name='recipe_detail'),
    path('contact', contact, name='contact'),
    path('create-story', create_story, name='create_story'),
    path('create-recipe', create_recipe, name='create_recipe'),
    path('edit-story/<int:pk>/', EditStory.as_view(), name='edit_story'),
    path('edit-recipe/<int:pk>/', EditRecipe.as_view(), name='edit_recipe'),
    path('delete_story/<int:id>/', delete_story, name='delete_story'),
    path('delete_recipe/<int:id>/', delete_recipe, name='delete_recipe'),


]

foodstories/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/',include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from accounts.models import User

class Story(models.Model):
    title = models.CharField(max_length=100)
    desription = models.TextField()
    text = models.TextField()
    image = models.ImageField(upload_to='images/')
    category = models.ForeignKey('Category', related_name='stories', on_delete=models.CASCADE)
    tags = models.ManyToManyField('Tag', related_name='stories')
    date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, related_name='stories', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.title
    

class Recipe(models.Model):
    title = models.CharField(max_length=100)
    desription = models.TextField()
    text = models.TextField()
    image = models.ImageField(upload_to='images/')
    # category
    date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, related_name='recipes', on_delete=models.CASCADE, null=True)


    def __str__(self):
        return self.title
    

class Category(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to='images/')

    def __str__(self):
        return self.title


class Tag(models.Model):
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title
    

class Comment(models.Model):
    story = models.ForeignKey(Story, related_name='comments', on_delete=models.CASCADE, null=True)
    text = models.TextField()
    user = models.ForeignKey(User, related_name='comments', on_delete=models.CASCADE, null=True)
    date = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.text
    

class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    subject = models.CharField(max_length=100)
    message = models.TextField()

    def __str__(self):
        return self.name

core/forms.py
from django import forms
from core.models import *

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email', 'subject', 'message']
        widgets = {
            'name': forms.TextInput(attrs={'class':'form-control','placeholder':'Your Name'}),
            'email': forms.EmailInput(attrs={'class':'form-control','placeholder':'Your Email'}),
            'subject': forms.TextInput(attrs={'class':'form-control','placeholder':'Subject'}),
            'message': forms.Textarea(attrs={'class':'form-control','placeholder':'Message'}),
        }

class StoryForm(forms.ModelForm):
    class Meta:
        model = Story
        fields = ['title', 'desription', 'text', 'image', 'category', 'tags']
        widgets = {
            'title': forms.TextInput(attrs={'class':'form-control','placeholder':'title'}),
            'desription': forms.Textarea(attrs={'class':'form-control','placeholder':'desription'}),
            'text': forms.Textarea(attrs={'class':'form-control','placeholder':'text'}),
            'images': forms.FileInput(attrs={'class':'form-control','placeholder':'image'}),
            'category': forms.Select(attrs={'class':'form-control','placeholder':'category'}),
            'tags': forms.SelectMultiple(attrs={'class':'form-control','placeholder':'tags'}),
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text',]
        widgets = {
            'text': forms.Textarea(attrs={'class':'form-control','placeholder':'Comment'}),
        }

class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['title', 'desription', 'text', 'image']
        widgets = {
            'title': forms.TextInput(attrs={'class':'form-control','placeholder':'title'}),
            'desription': forms.Textarea(attrs={'class':'form-control','placeholder':'desription'}),
            'text': forms.Textarea(attrs={'class':'form-control','placeholder':'text'}),
            'images': forms.FileInput(attrs={'class':'form-control','placeholder':'image'}),
            
        }

core/views.py
from django.shortcuts import render, redirect
from core.models import *
from core.forms import *
from django.views.generic import UpdateView
from django.urls import reverse_lazy


def home(request):
    stories = Story.objects.order_by('-id')[:4]
    last_story = stories.first()
    categories = Category.objects.all()
    holiday = Story.objects.filter(category__title='Holiday')
    context = {
        'stories': stories,
        'last_story': last_story,
        'categories': categories,
        'holiday': holiday,
    }
    return render(request, 'index.html', context)


def story_detail(request, id):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save()
            comment.story = Story.objects.get(id=id)
            comment.user = request.user
            comment.save()
            return redirect('core:story_detail', id=id)
    story = Story.objects.get(id=id)
    form = CommentForm()
    categories = Category.objects.all()
    recents = Story.objects.order_by('-id')[:2]
    tags = Tag.objects.all()
    context = {
        'data': story,
        'categories': categories,
        'recents': recents,
        'tags': tags,
        'form': form,
        }
    return render(request, 'single.html', context)

def about(request):
    categories = Category.objects.all()
    context = {
        'categories': categories
    }
    return render(request, 'about.html', context)



def stories(request):
    search = request.GET.get('search')
    cat = request.GET.get('cat')
    tag = request.GET.get('tag')
    stories = Story.objects.order_by('-id')
    if search:
        stories = stories.filter(title__icontains=search)
    if cat:
        stories = stories.filter(category__title=cat)
    if tag:
        stories = stories.filter(tags__title=tag)
    categories = Category.objects.all()
    context = {
        'stories':stories,
        'categories':categories,
    }
    return render(request, 'stories.html', context)

def recipes(request):
    search = request.GET.get('search')
    recipes = Recipe.objects.order_by('-id')
    if search:
        recipe = recipes.filter(title__icontains=search)
    categories = Category.objects.all()
    context = {
        'recipes':recipes,
        'categories':categories,
    }
    return render(request, 'recipes.html', context)

def recipe_detail(request, id):
    recipe = Recipe.objects.get(id=id)
    categories = Category.objects.all()
    tags = Tag.objects.all()
    recents = Recipe.objects.order_by('-id')[:2]
    context = {
        'data' : recipe,
        'categories': categories,
        'tags':tags,
        'recent':recents
    }
    return render(request,'single-recipe.html', context)

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
    form = ContactForm()
    categories = Category.objects.all()
    context = {
        'categories':categories,
        'form':form
    }
    return render(request, 'contact.html', context)

def create_story(request):
    if request.method == 'POST':
        form = StoryForm(request.POST, request.FILES)
        if form.is_valid():
            story = form.save()
            story.user = request.user
            story.save()
            return redirect('accounts:profile', id=request.user.id)
    form = StoryForm()
    context = {
        'form':form
    }
    return render(request, 'create-story.html', context)

def create_recipe(request):
    if request.method == 'POST':
        form = RecipeForm(request.POST, request.FILES)
        if form.is_valid():
            recipe = form.save()
            recipe.user = request.user
            recipe.save()
            return redirect(f'/accounts/profile/{request.user.id}/#resept')
    form = RecipeForm()
    context = {
        'form':form
    }
    return render(request, 'create-recipe.html', context)

class EditStory(UpdateView):
    template_name = "create-story.html"
    model = Story
    form_class = StoryForm
    
    def get_success_url(self):
        return reverse_lazy('accounts:profile', args=[self.request.user.id])

class EditRecipe(UpdateView):
    template_name = "create-recipe.html"
    model = Recipe
    form_class = RecipeForm
    
    def get_success_url(self):
        return reverse_lazy('accounts:profile', args=[self.request.user.id])

def delete_story(request, id):
    story = Story.objects.get(id=id)
    story.delete()
    return redirect('accounts:profile', id=request.user.id)

def delete_recipe(request, id):
    recipe = Recipe.objects.get(id=id)
    recipe.delete()
    return redirect('accounts:profile', id=request.user.id)

core/templates/includes/footer.html
<footer class="ftco-footer ftco-footer-2 ftco-section">
    <div class="container">
        <div class="row mb-5">
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Stories</h2>
                    <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
                    <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                        <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4 ml-md-5">
                    <h2 class="ftco-heading-2">Information</h2>
                    <ul class="list-unstyled">
                        <li><a href="#" class="py-2 d-block">Terms of Uses</a></li>
                        <li><a href="#" class="py-2 d-block">About Stories</a></li>
                        <li><a href="#" class="py-2 d-block">Privacy Policy</a></li>
                        <li><a href="#" class="py-2 d-block">Accessibility Help</a></li>
                        <li><a href="#" class="py-2 d-block">Advertise with us</a></li>
                    </ul>
                </div>
            </div>
             <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Categories</h2>
                    <ul class="list-unstyled">
                        {% for category in categories %}
                        <li>
                            <a href="{% url 'core:stories' %}?cat={{category.title}}" class="py-2 d-block">{{category.title}}</a>

                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div> 
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Have a Questions?</h2>
                    <div class="block-23 mb-3">
                        <ul>
                            <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span>
                            </li>
                            <li><a href="#"><span class="icon icon-phone"></span><span
                                class="text">+2 392 3929 210</span></a></li>
                            <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@yourdomain.com</span></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-center">

                <p>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;
                    <script>
                        document.write(new Date().getFullYear());
                    </script>
                    All rights reserved | This template is made with <i class="icon-heart color-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </p>
            </div>
        </div>
    </div>
</footer>

core/templates/includes/me.html
{% if request.user.is_authenticated %}
<div class="sidebar-wrap">
                    <div class="sidebar-box p-4 about text-center ftco-animate">
                        <h2 class="heading mb-4">About Me</h2>
                            {% if user.image %}
                            <img src="{{user.image.url}}" class="img-fluid" alt="Colorlib Template">
                            {% else %}
                            <img style="border: 1px solid rgb(219, 219, 219);" src="https://t4.ftcdn.net/jpg/02/15/84/43/360_F_215844325_ttX9YiIIyeaR7Ne6EaLLjMAmy4GvPC69.jpg" class="img-fluid" alt="Colorlib Template">
                            {% endif %}
                        <div class="text pt-4">
                            <p>Hi! My name is <strong>{{user.first_name}} {{user.last_name}}</strong>, {{user.info}}</p>
                        </div>
                    </div>
                    <div class="sidebar-box p-4 ftco-animate">
                        <form action="{% url 'core:stories' %}" class="search-form">
                            <div class="form-group">
                                <span class="icon icon-search"></span>
                                <input name="search" type="text" class="form-control" placeholder="Search">
                            </div>
                        </form>
                    </div>
                </div>
{% else %}
{% endif %}

core/templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="container">
        <a class="navbar-brand" href="{% url 'core:home' %}">Stories<span>.</span></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="oi oi-menu"></span> Menu
    </button>

        <div class="collapse navbar-collapse" id="ftco-nav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item"><a href="{% url 'core:home' %}" class="nav-link {% if request.resolver_match.url_name == 'home'%}active{% endif %}">Home</a></li>
                <li class="nav-item"><a href="{% url 'core:about' %}" class="nav-link {% if request.resolver_match.url_name == 'about'%}active{% endif %}">About</a></li>
                <li class="nav-item"><a href="{% url 'core:stories' %}" class="nav-link {% if request.resolver_match.url_name == 'stories'%}active{% endif %}">Stories</a></li>
                <li class="nav-item"><a href="{% url 'core:recipes' %}" class="nav-link {% if request.resolver_match.url_name == 'recipes'%}active{% endif %}">Recipes</a></li>
                <li class="nav-item"><a href="{% url 'core:contact' %}" class="nav-link {% if request.resolver_match.url_name == 'contact'%}active{% endif %}">Contact</a></li>
                {% if request.user.is_authenticated %}
                <li><a href="{% url 'accounts:profile' request.user.id %}" class="btn btn-black px-3 px-md-4 py-3">{{request.user.username}}</a></li>
                {% else %}
                <li><a href="{% url 'accounts:login' %}" class="btn btn-black px-3 px-md-4 py-3 mr-2">Login</a></li>
                <li><a href="{% url 'accounts:register' %}" class="btn btn-black px-3 px-md-4 py-3">Register</a></li>
                {% endif %}
                

            </ul>
        </div>
    </div>
</nav>