accounts/urls.py
from django.urls import path
from accounts.views import *
from django.contrib.auth.views import LogoutView

app_name = 'accounts'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', Login.as_view(), name='login'),
    path('profile/<int:id>/', profile, name='profile'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('edit-profile/<int:pk>/', EditProfile.as_view(), name='edit_profile'),
    path('forget-password/',ForgetPassword.as_view(),name='forget-password'),
    path('password-reset-confirm/<str:uidb64>/<str:token>',CustomPasswordResetConfirmView.as_view(),name='password-reset-confirm'),
]

core/urls.py
from django.urls import path
from core.views import *

app_name = 'core'

urlpatterns = [
    path('', home, name='home'),
    path('story/<int:id>/', story_detail, name='story_detail'),
    path('about/', about, name='about'),
    path('stories/', stories, name='stories'),
    path('recipes/', recipes, name='recipes'),
    path('recipe/<int:id>/', recipe_detail, name='recipe_detail'),
    path('contact', contact, name='contact'),
    path('create-story', create_story, name='create_story'),
    path('create-recipe', create_recipe, name='create_recipe'),
    path('edit-story/<int:pk>/', EditStory.as_view(), name='edit_story'),
    path('edit-recipe/<int:pk>/', EditRecipe.as_view(), name='edit_recipe'),
    path('delete_story/<int:id>/', delete_story, name='delete_story'),
    path('delete_recipe/<int:id>/', delete_recipe, name='delete_recipe'),


]

foodstories/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/',include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    image = models.ImageField(upload_to='images/',null=True, blank=True)
    info = models.TextField()

    

accounts/forms.py
from django import forms
from accounts.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm, PasswordResetForm, SetPasswordForm




class RegisterForm(UserCreationForm):
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Password'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Password'}))

    class Meta:
        model = User
        fields = ['first_name', 'last_name','username', 'email', 'password1', 'password2', 'image', 'info', ]
        widgets = {
            'first_name': forms.TextInput(attrs={'class':'form-control','placeholder':'First Name'}),
            'last_name': forms.TextInput(attrs={'class':'form-control','placeholder':'Last Name'}),
            'username': forms.TextInput(attrs={'class':'form-control','placeholder':'Username'}),
            'image': forms.FileInput(attrs={'class':'form-control','placeholder':'Image'}),
            'info' : forms.Textarea(attrs={'class':'form-control','placeholder':'Info'}),
            'email': forms.EmailInput(attrs={'class':'form-control','placeholder':'Email'}),
        }

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Username'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Password'}))

    class Meta:
        model = User
        fields = ['username', 'password']
        widgets = {
            'username': forms.TextInput(attrs={'class':'form-control','placeholder':'Username'}),
        }


class EditProfileForm(UserChangeForm):
    class Meta:
        model = User 
        fields = ['first_name', 'last_name','username', 'email', 'image', 'info',]
        widgets = {
            'first_name': forms.TextInput(attrs={'class':'form-control','placeholder':'First Name'}),
            'last_name': forms.TextInput(attrs={'class':'form-control','placeholder':'Last Name'}),
            'username': forms.TextInput(attrs={'class':'form-control','placeholder':'Username'}),
            'image': forms.FileInput(attrs={'class':'form-control','placeholder':'Image'}),
            'info' : forms.Textarea(attrs={'class':'form-control','placeholder':'Info'}),
            'email': forms.EmailInput(attrs={'class':'form-control','placeholder':'Email'}),
        }


class ForgotPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control', 'placeholder':'Email'}))

    class Meta:
        model = User
        fields = ['email']
        widgets = {
            'email': forms.EmailInput(attrs={'class':'form-control', 'placeholder':'Email'}),
        }

class ForgotPasswordConfirmForm(SetPasswordForm):
    new_password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'New Password'}))
    new_password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'Confirm New Password'}))
    class Meta:
        model = User
        fields = ['new-password1', 'new_password2']

accounts/views.py
from django.shortcuts import render
from accounts.models import User
from django.views.generic import CreateView, UpdateView
from accounts.forms import *
from django.contrib.auth.views import LoginView, PasswordResetView, PasswordResetConfirmView
from django.urls import reverse_lazy
from core.models import *

class RegisterView(CreateView):
    template_name = "register.html"
    model = User
    form_class = RegisterForm
    success_url = reverse_lazy('accounts:login')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context
    

class Login(LoginView):
    template_name = "login.html"
    form_class = LoginForm
    success_url = '/'
    model = User
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context


def profile(request, id):
    categories = Category.objects.all()
    user = User.objects.get(id=id)
    context  = {
        'user' : user,
        'categories':categories
    }
    return render(request, 'user-profile.html', context)

class EditProfile(UpdateView):
    template_name = "register.html"
    model = User
    form_class = EditProfileForm
    
    def get_success_url(self):
        return reverse_lazy('accounts:profile', args=[self.request.user.id])

class ForgetPassword(PasswordResetView):
    template_name= "forget-password.html"
    success_url = reverse_lazy('accounts:login')
    form_class = ForgotPasswordResetForm
    email_template_name = "forget-password-email.html"

class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = "change-password.html"
    success_url = reverse_lazy('accounts:login')
    form_class = ForgotPasswordConfirmForm

accounts/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Stories - Free Bootstrap 4 Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,400i,700,700i,900,900i" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">

    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">

    <link rel="stylesheet" href="{% static 'css/aos.css' %}">

    <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
</head>

<body>

{% include "includes/navbar.html" %}

{% block content %}

{% endblock %}

{% include "includes/footer.html" %}

<!-- loader -->
<div id="ftco-loader" class="show fullscreen">
    <svg class="circular" width="48px" height="48px">
    <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
    <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
            stroke="#F96D00"/>
</svg>
</div>


<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/jquery.stellar.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/aos.js' %}"></script>
<script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
<script src="{% static 'js/scrollax.min.js' %}"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
<script src="{% static 'js/google-map.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<script src="https://kit.fontawesome.com/a076d05399.js"></script>

</body>

</html>

accounts/templates/change-password.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="ftco-section contact-section register">
        <div class="container">
            <div class="row block-9 justify-content-center">
                <div class="col-md-6 order-md-last d-flex">
                    <form action="#" method="post" enctype="multipart/form-data" class="bg-light p-5 contact-form">
                        {% csrf_token %}
                        {{form.non_field_errors}}
                        <div class="form-group">
                            <h4 class="reset center">Change your password</h4>
                            <h6 class="center">Please choose a new password to finish signing in.</h6>
                        </div>
                        <div class="form-group">
                            {{form.new_password1}}
                            {{form.new_password1.errors}}
                        </div>
                        <div class="form-group">
                            {{form.new_password2}}
                            {{form.new_password2.errors}}
                        </div>
                        <div class="form-group center">
                            <input type="submit" value="Change password" class="btn btn-primary py-3 px-5">
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </section>
{% endblock %}

accounts/templates/forget-password-email.html
{% load i18n %}
{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
Sifrenizi deyismek ucun bura tiklayin!
{{ protocol }}://{{ domain }}{% url 'accounts:password-reset-confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

accounts/templates/forget-password.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="ftco-section contact-section register">
        <div class="container">
            <div class="row block-9 justify-content-center">
                <div class="col-md-6 order-md-last d-flex">
                    <form action="#" method="post" enctype="multipart/form-data" class="bg-light p-5 contact-form">
                        {% csrf_token %}
                        {{ form.non_field_errors }}
                        <div class="form-group">
                            <h4 class="reset center">Reset password</h4>
                            <h6 class="center">Please enter your email address to request a password reset.</h6>
                        </div>
                        <div class="form-group">
                            {{form.email}}
                            {{form.email.errors}}
                        </div>
                        <div class="form-group center">
                            <input type="submit" value="Reset password" class="btn btn-primary py-3 px-5">
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </section>
{% endblock %}

accounts/templates/login.html
{% extends 'base.html' %}

{% block content %}
<section class="ftco-section contact-section register">
        <div class="container">
            <div class="row block-9 justify-content-center">
                <div class="col-md-6 order-md-last d-flex">
                    <form method="post" action="#" class="bg-light p-5 contact-form">
                        {% csrf_token %}
                        <a class="navbar-brand center" href="#">Stories<span>.</span></a>
                        <div class="form-group">
                            {{ form.username }}
                            {{ form.username.errors }}
                        </div>
                        <div class="form-group">
                            {{ form.password }}
                            {{ form.password.errors }}
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Login" class="btn btn-primary py-3 px-5">
                            <a href="{% url 'accounts:forget-password' %}" class="forgot-password">Forgot password?</a>
                        </div>
                        <div class="form-group">
                            <a href="{% url 'accounts:register' %}" class="">Don't have an account? Sign up</a>
                        </div>
			<div class="form-group center">
                            <a href="#" class="social"><i class="fa fa-facebook social-login fb-color"></i></a>
                            <a href="#" class="social"><i class="fa fa-google-plus social-login google-color"></i></a>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </section>
{% endblock %}

accounts/templates/register.html
{% extends 'base.html' %}


{% block content %}

<!-- END nav -->
<section class="ftco-section contact-section register">
        <div class="container">
            <div class="row block-9 justify-content-center">
                <div class="col-md-6 order-md-last d-flex">
                    <form method="post" enctype="multipart/form-data" action="#" class="bg-light p-5 contact-form">
                    {% csrf_token %}
                        <a class="navbar-brand center" href="#">Stories<span>.</span></a>
                        <div class="form-group">
                            {{ form.first_name }}
                            {{ form.first_name.errors }}
                        </div>
                        <div class="form-group">
                            {{ form.last_name }}
                            {{ form.last_name.errors }}
                        </div>
                        <div class="form-group">
                            {{ form.username }}
                            {{ form.username.errors }}
                        </div>
                        <div class="form-group">
                            {{ form.email }}
                            {{ form.email.errors }}
                        </div>
                        <div class="form-group">
                            {{ form.info }}
                            {{ form.info.errors }}
                        </div>
                        <div class="form-group">
                            {{ form.image }}
                            {{ form.image.errors }}
                        </div>
                        <div class="form-group">
                            {{ form.password1 }}
                            {{ form.password1.errors }}
                        </div>
                        <div class="form-group">
                            {{ form.password2 }}
                            {{ form.password2.errors }}
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Register" class="btn btn-primary py-3 px-5">
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </section>





{% endblock %}

accounts/templates/user-profile.html
{% extends 'base.html' %}

{% block content %}
 <section class="ftco-section ftco-no-pt ">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="user-profile-side-bar sidebar-wrap">
                        <div class="sidebar-box p-4 about text-center ftco-animate">
                            <h2 class="heading mb-4">About Me</h2>
                            {% if user.image %}
                            <img src="{{user.image.url}}" class="img-fluid" alt="Colorlib Template">
                            {% else %}
                            <img style="border: 1px solid rgb(219, 219, 219);" src="https://t4.ftcdn.net/jpg/02/15/84/43/360_F_215844325_ttX9YiIIyeaR7Ne6EaLLjMAmy4GvPC69.jpg" class="img-fluid" alt="Colorlib Template">
                            {% endif %}
                            <div class="text pt-4">
                                <h2>{{user.first_name}} {{user.last_name}}</h2>
                                <p>{{user.info}}</p>
                            </div>
                        </div>
                        <div class="sidebar-box ftco-animate user-profile">

                            <a href="{% url 'accounts:edit_profile' request.user.id%}" class="btn btn-hover-color py-2">Edit Profile</a>

                        </div>
                        <div class="sidebar-box ftco-animate user-profile">
                            <a href="{% url 'core:create_story' %}" class="btn btn-hover-color py-2">Create story </a>
                        </div>
                        <div class="sidebar-box ftco-animate user-profile">
                            <a href="{% url 'core:create_recipe' %}" class="btn btn-hover-color py-2">Create recipe </a>
                        </div>
                        <div class="sidebar-box ftco-animate user-profile pb-4">
                            <form method="post" action="{% url 'accounts:logout' %}">
                            {% csrf_token %}
                              <button type="submit" class="btn btn-hover-color py-2">Logout</button>  
                            </form>
                        </div>
                        
                    </div>
                </div>

                <div class="col-lg-9">
                    <div class="row">
                        <div class="col-md-12 heading-section ftco-animate">
                            <h2 class="mb-4"><span>My stories</span></h2>
                        </div>
                    </div>
                    <div class="row">
                        {% if user.stories.all %}
                        {% for story in user.stories.all %}
                        <div class="col-md-4 ftco-animate">
                            <div class="blog-entry">
                                <a class="img-2">

                                    <div class="user-events__edit">
                                        <a style="color: white;" href="{% url 'core:edit_story' story.id%}" type="button" class="edit-event"><i class="fa fa-edit" aria-hidden="true"></i></a>
                                        <button type="button" class="delete-event"data-toggle="modal" data-target="#exampleModal{{story.id}}"><i class="fa fa-trash" aria-hidden="true"></i></button>
                                    </div>

                                    <img src="{{story.image.url}}" class="img-fluid" alt="Colorlib Template">
                                </a>
                                <div class="text pt-3">
                                    <p class="meta d-flex"><span class="pr-3">{{story.category}}</span><span class="ml-auto pl-3">{{story.date | date:"M ,d ,Y"}}</span>
                                    </p>
                                    <h3><a href="{% url 'core:story_detail' story.id %}">{{story.title}}</a></h3>
                                    <p class="mb-0"><a href="{% url 'core:story_detail' story.id %}" class="btn btn-black py-2">Read More <span
                                        class="icon-arrow_forward ml-4"></span></a></p>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                        {% else %}
                <p>Your stories and recipes will be shown here!</p>
                {% endif %}
                        <div class="col-md-12 heading-section ftco-animate">
                            <h2 class="mb-4" id="resept"><span>My recipes</span></h2>
                        </div>
                        {% if user.recipes.all %}
                        {% for recipe in user.recipes.all %}
                        <div class="col-md-4 ftco-animate">
                            <div class="blog-entry">
                                <a class="img-2">

                                    <div class="user-events__edit">
                                        <a style="color: white;" href="{% url 'core:edit_recipe' recipe.id%}" type="button" class="edit-event"><i class="fa fa-edit" aria-hidden="true"></i></a>
                                        <button type="button" class="delete-event"data-toggle="modal" data-target="#recipeModal{{recipe.id}}"><i class="fa fa-trash" aria-hidden="true"></i></button>
                                    </div>

                                    <img src="{{recipe.image.url}}" class="img-fluid" alt="Colorlib Template">
                                </a>
                                <div class="text pt-3">
                                    <p class="meta d-flex"><span class="pr-3">{{recipe.category}}</span><span class="ml-auto pl-3">{{recipe.date | date:"M ,d ,Y"}}</span>
                                    </p>
                                    <h3><a href="{% url 'core:recipe_detail' recipe.id %}">{{recipe.title}}</a></h3>
                                    <p class="mb-0"><a href="{% url 'core:recipe_detail' recipe.id %}" class="btn btn-black py-2">Read More <span
                                        class="icon-arrow_forward ml-4"></span></a></p>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
                {% else %}
                <p>Your stories and recipes will be shown here!</p>
                {% endif %}


            </div>
        </div>
    </section>
    {% for story in user.stories.all %}
    <div class="modal fade" id="exampleModal{{story.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Delete Story?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete "{{story.title}}"?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <a style="color: white;" href="{%url 'core:delete_story' story.id%}" type="button" class="btn btn-primary">Delete</a>
      </div>
    </div>
  </div>
</div>
    {% endfor %}

{% for recipe in user.recipes.all %}
    <div class="modal fade" id="recipeModal{{recipe.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Delete Recipe?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete "{{recipe.title}}"?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <a style="color: white;" href="{%url 'core:delete_recipe' recipe.id%}" type="button" class="btn btn-primary">Delete</a>
      </div>
    </div>
  </div>
</div>
    {% endfor %}
{% endblock %}